name: Daily Email Sender

on:
  schedule:
    - cron: '0 10 * * *'   # 10:00 AM UTC
    - cron: '0 12 * * *'   # 12:00 PM UTC
    - cron: '0 14 * * *'   # 2:00 PM UTC
    - cron: '0 16 * * *'   # 4:00 PM UTC
  workflow_dispatch:

jobs:
  send-emails:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run email script
      run: python send_emails.py

    - name: Commit counter update
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add counter.txt
        git commit -m "Update counter.txt" || echo "No changes"
        git push
